name: if-test

on:
  workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      NAME: cpj
    if: ${{ env.NAME == 'cpj' }}
    steps:
      - id: step1
        run: echo "hello my world"
