name: if-test

on:
  workflow_dispatch
env:
  NAME: cpj

jobs:
  job1:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - id: step1
        run: echo "hello my world"
      - id: step2
        run: echo $NAME
  job2:
    needs: job1
    runs-on: ubuntu-latest
    if: ${{ failure(job1) }}
    steps:
      - id: step1
        run: echo "hello my world"
      - id: step2
        run: echo $NAME
