name: needs-test

on:
  workflow_dispatch
env:
  NAME: cpj

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - id: step1
        run: echo "hello my world1"
  job2:
    runs-on: ubuntu-latest
    steps:
      - id: step1
        run: echo "hello my world2"
  job3:
    runs-on: ubuntu-latest
    steps:
      - id: step1
        run: echo "hello my world3"
  job4:
    needs: [job1,job6]
    runs-on: ubuntu-latest
    steps:
      - id: step1
        run: echo "hello my world4"
  job5:
    needs: [job1,job2]
    runs-on: ubuntu-latest
    steps:
      - id: step1
        run: echo "hello my world5"
  job6:
    needs: [job3,job5]
    runs-on: ubuntu-latest
    steps:
      - id: step1
        run: echo "hello my world6"
